.TH VERSION-FROM-POM "1" "August 2012" "version-from-pom #VERSION#" "Laxative manual"
.SH NAME
Laxative - pom version scraper
.SH SYNOPSIS
.BI "version-from-pom " path
.SH DESCRIPTION
Prints the artifact's version to stdout given a
.I path
to a Maven pom.xml file.
.SH AUTHORS
Nick Robinson-Wall <nick@robinson-wall.com>
.SH SEE ALSO
.BR lax (1)

.BR lax-build (1),
.BR lax-fakelog (1),
.BR lax-make (1),
.BR lax-mock (1),
.BR lax-updatelog (1),
.BR lax-version (1)
